// <auto-generated />
using System;
using DepartmentOfVeterans.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DepartmentOfVeterans.Persistence.Migrations
{
    [DbContext(typeof(DepartmentOfVeteransDbContext))]
    partial class DepartmentOfVeteransDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DepartmentOfVeterans.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("3540f776-84dd-4dcd-a90b-0f72203dd574"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Karl",
                            Gender = "male",
                            LastName = "Johnson",
                            Picture = "https://randomuser.me/api/portraits/med/men/6.jpg",
                            UserEmail = "karl.johnson@example.com",
                            UserName = "bigpeacock170",
                            UserPassword = "scuba1"
                        },
                        new
                        {
                            UserId = new Guid("5d39272c-7756-4c90-bcd7-706248244211"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Margot",
                            Gender = "female",
                            LastName = "Roche",
                            Picture = "https://randomuser.me/api/portraits/med/women/21.jpg",
                            UserEmail = "margot.roche@example.com",
                            UserName = "goldenrabbit215",
                            UserPassword = "tiger234"
                        },
                        new
                        {
                            UserId = new Guid("a9a1364a-c39a-440c-83bc-b39ae9b45e27"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Potishana",
                            Gender = "Male",
                            LastName = "Buryak",
                            Picture = "https://randomuser.me/api/portraits/med/men/6.jpg",
                            UserEmail = "potishana.buryak@example.com",
                            UserName = "tinymeercat589",
                            UserPassword = "betty05"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
